# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253094

# Verify the operating system removes all software components after updated
# versions have been installed.
#
# Check if YUM is configured to remove unneeded packages with the following
# command:
#
#     $ sudo grep -i clean_requirements_on_remove /etc/dnf/dnf.conf
#     clean_requirements_on_remove=True
#
# If "clean_requirements_on_remove" is not set to either "1", "True", or
# "yes", commented out, or is missing from "/etc/dnf/dnf.conf", this is
# a finding.


- name: TOSS-04-040500 - YUM must remove all software components after updated versions have been installed on TOSS.
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    line: clean_requirements_on_remove=True
  when:
    - toss_04_040500 | bool
  tags:
    - V-253094
    - SRG-OS-000437-GPOS-00194
    - TOSS-04-040500
    - DISA-STIG-TOSS-04-040500
    - low_severity
    - CCI-002617
