# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-252938

# Verify TOSS is not configured to reboot the system when Ctrl-Alt-Delete
# is pressed seven times within two seconds with the following command:
#
#     $ sudo grep -i ctrl /etc/systemd/system.conf
#     CtrlAltDelBurstAction=none
#
# If the "CtrlAltDelBurstAction" is not set to "none", commented out, or
# is missing, this is a finding.


- name: TOSS-04-010360 - The systemd Ctrl-Alt-Delete burst key sequence in TOSS must be disabled.
  ansible.builtin.lineinfile:
    path: /etc/systemd/system.conf
    regexp: '^#?CtrlAltDelBurstAction='
    line: 'CtrlAltDelBurstAction=none'
    state: present
    backup: true
  when:
    - toss_04_010360 | bool
  tags:
    - V-252938
    - SRG-OS-000480-GPOS-00227
    - TOSS-04-010360
    - DISA-STIG-TOSS-04-010360
    - high_severity
    - CCI-000366
    - NASA-ASCS-20365
    - DISA-STIG-RHEL-08-040172
