# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253005

# Verify that an audit event is generated for any successful/unsuccessful use
# of the "chsh" command by performing the following command to check the file
# system rules in "/etc/audit/audit.rules":
#
#     $ sudo grep -w chsh /etc/audit/audit.rules
#     -a always,exit -F path=/usr/bin/chsh -F perm=x -F auid>=1000 -F auid!=unset -k priv_cmd
#
# If the command does not return a line, or the line is commented out,
# this is a finding.


- name: TOSS-04-030510 - Successful/unsuccessful uses of the "chsh" command in TOSS must generate an audit record.
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/audit.rules
    line: -a always,exit -F path=/usr/bin/chsh -F perm=x -F auid>=1000 -F auid!=unset -k priv_cmd
  notify: Build auditd rules
  when:
    - toss_04_030510 | bool
  tags:
    - V-253005
    - SRG-OS-000037-GPOS-00015
    - TOSS-04-030510
    - DISA-STIG-TOSS-04-030510
    - medium_severity
    - CCI-000130
    - CCI-000135
    - CCI-000169
    - CCI-000172
    - CCI-002884
