# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253079

# Check to see if the sendmail package is installed with the following command:
#
#     $ sudo yum list installed sendmail
#
# If the sendmail package is installed, this is a finding.


- name: TOSS-04-040250 - TOSS must not have the sendmail package installed.
  ansible.builtin.package:
    name: sendmail
    state: absent
  when:
    - toss_04_040250 | bool
  tags:
    - V-253079
    - SRG-OS-000095-GPOS-00049
    - TOSS-04-040250
    - DISA-STIG-TOSS-04-040250
    - medium_severity
    - CCI-000381
    - DISA-STIG-RHEL-08-040002
