# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-252979

# Verify the audit logs are owned by user root.
#
# First, determine where the audit logs are stored with the following command:
#
#     $ sudo grep -iw log_file /etc/audit/auditd.conf
#     log_file = /var/log/audit/audit.log
#
# Using the location of the audit log file, check if the audit log is owned by
# user "root" with the following command:
#
#     $ sudo ls -l /var/log/audit/audit.log
#     -rw------- 1 root root 908084 Jul 19 23:10 /var/log/audit/audit.log
#
# If the audit log is not owned by user "root", this is a finding.


- name: TOSS-04-030140 - TOSS audit logs must be owned by user root to prevent unauthorized read access.
  ansible.builtin.file:
    path: /var/log/audit/audit.log
    owner: root
    mode: '0600'
    state: touch
  when:
    - toss_04_030140 | bool
  tags:
    - V-252979
    - SRG-OS-000057-GPOS-00027
    - TOSS-04-030140
    - DISA-STIG-TOSS-04-030140
    - medium_severity
    - CCI-000162
    - CCI-000163
    - CCI-000164
