# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253093

# Verify the NX (no-execution) bit flag is set on the system.
#
# Check that the no-execution bit flag is set with the following commands:
#
#     $ sudo dmesg | grep NX
#     [ 0.000000] NX (Execute Disable) protection: active
#
# If "dmesg" does not show "NX (Execute Disable) protection" active, check
# the cpuinfo settings with the following command:
#
#     $ sudo less /proc/cpuinfo | grep -i flags
#     flags : fpu vme de pse tsc ms nx rdtscp lm constant_tsc
#
# If "flags" does not contain the "nx" flag, this is a finding.


- name: TOSS-04-040490 - TOSS must implement non-executable data to protect its memory from unauthorized code execution.
  block:
    - name: TOSS-04-040490 - Check that the no-execution bit flag is set
      ansible.builtin.shell:
        cmd: 'set -o pipefail && dmesg | grep "NX (Execute Disable) protection: active"'
      register: execute_bit_flag
      failed_when: execute_bit_flag.rc not in [0, 1]
      changed_when: false
      check_mode: false
    - name: TOSS-04-040490 - Check the cpuinfo settings for the nx flag
      ansible.builtin.command: 'grep -i "flags\(\s\|\S\)\+nx" /proc/cpuinfo'
      register: cpuinfo_settings
      failed_when: cpuinfo_settings.rc not in [0, 1]
      when: execute_bit_flag.rc == 1
      changed_when: false
    - name: TOSS-04-040490 - Check that both flags are set
      ansible.builtin.assert:
        that:
          - execute_bit_flag.rc == 0 or cpuinfo_settings.rc == 0
        fail_msg: "The NX bit execute protection is not set and must be enabled in the system BIOS"
        quiet: true
  when:
    - toss_04_040490 | bool
  tags:
    - V-253093
    - SRG-OS-000433-GPOS-00192
    - TOSS-04-040490
    - DISA-STIG-TOSS-04-040490
    - medium_severity
    - CCI-002824
    - DISA-STIG-RHEL-08-010420
