# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-252962

# Verify local interactive users on TOSS have a home directory assigned
# with the following command: $ sudo pwck -r user 'lp': directory '/var/spool/lpd'
# does not exist user 'news': directory '/var/spool/news' does not exist user
# 'uucp': directory '/var/spool/uucp' does not exist user 'www-data': directory
# '/var/www' does not exist Ask the System Administrator (SA) if any users found
# without home directories are local interactive users. If the SA is unable to
# provide a response, check for users with a User Identifier (UID) of 1000 or
# greater with the following command: $ sudo awk -F: '($3>=1000)&&($7
# !~ /nologin/){print $1, $3, $6}' /etc/passwd If any interactive users do not
# have a home directory assigned, this is a finding.


- name: TOSS-04-020230 - All TOSS local interactive users must have a home directory assigned in the /etc/passwd file.
  block:
    - name: Find all local interactive users' home directory
      ansible.builtin.shell:
        cmd: "find $(awk -F: '($3>=1000)&&($7 !~ /nologin/)&&($7 !~ /false/){print $6}' /etc/passwd) -xdev -maxdepth 0"
      changed_when: false
      check_mode: false
      failed_when: home_dirs.rc not in [0,1]
      register: home_dirs
    - name: Display any local interactive users without home directories
      ansible.builtin.debug:
        var: item
        verbosity: 1
      when: home_dirs.rc == 1
      loop: '{{ home_dirs.stderr_lines }}'
    - name: Check that there aren't any missing home directories
      ansible.builtin.fail:
        msg: "There is at least interactive user whose home directory doesn't exist"
      when: home_dirs.rc == 1
  when:
    - toss_04_020230 | bool
  tags:
    - V-252962
    - SRG-OS-000480-GPOS-00227
    - SV-252962r824210_rule
    - TOSS-04-020230
    - DISA-STIG-TOSS-04-020230
    - medium_severity
    - CCI-000366
    - hpc_issue
