# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253033

# Verify the TOSS audit Daemon is configured to label all off-loaded
# audit logs, with the following command:
#
#     $ sudo grep "name_format" /etc/audit/auditd.conf
#     name_format = hostname
#
# If the "name_format" option is not "hostname", "fqd", or "numeric",
# or the line is commented out, this is a finding.


- name: TOSS-04-030910 - TOSS must label all off-loaded audit logs before sending them to the central log server.
  block:
    - name: TOSS-04-030910 - Check for duplicate values
      ansible.builtin.lineinfile:
        path: /etc/audit/auditd.conf
        create: false
        regexp: (?i)^\s*name_format\s*=\s*
        state: absent
      check_mode: true
      changed_when: false
      register: dupes
    - name: TOSS-04-030910 - Deduplicate values from /etc/audit/auditd.conf
      ansible.builtin.lineinfile:
        path: /etc/audit/auditd.conf
        create: false
        regexp: (?i)^\s*name_format\s*=\s*
        state: absent
      when: dupes.found is defined and dupes.found > 1
    - name: TOSS-04-030910 - Insert correct line to /etc/audit/auditd.conf
      ansible.builtin.lineinfile:
        path: /etc/audit/auditd.conf
        create: true
        regexp: (?i)^\s*name_format\s*=\s*
        line: name_format = hostname
        state: present
        mode: '0640'
  when:
    - toss_04_030910 | bool
  tags:
    - V-253033
    - SRG-OS-000342-GPOS-00133
    - TOSS-04-030910
    - DISA-STIG-TOSS-04-030910
    - medium_severity
    - CCI-001851
    - DISA-STIG-RHEL-08-030062
