# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253053

# Verify the TOSS audit daemon is configured to resolve audit information
# before writing to disk, with the following command:
#
#     $ sudo grep "log_format" /etc/audit/auditd.conf
#     log_format = ENRICHED
#
# If the "log_format" option is not "ENRICHED", or the line is commented
# out, this is a finding.


- name: TOSS-04-031360 - TOSS must resolve audit information before writing to disk.
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    create: true
    regexp: (?i)^\s*log_format\s*=\s*
    line: log_format = ENRICHED
    state: present
    mode: '640'
  when:
    - toss_04_031360 | bool
  tags:
    - V-253053
    - SRG-OS-000480-GPOS-00227
    - TOSS-04-031360
    - DISA-STIG-TOSS-04-031360
    - low_severity
    - CCI-000366
