# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253137

#  checkid: C-56590r825081_chk
#  checktext: |-
#    Verify the operating system is configured to enable DAC on hardlinks with the following commands:
#    Check the status of the fs.protected_hardlinks kernel parameter.
#      $ sudo sysctl fs.protected_hardlinks
#        fs.protected_hardlinks = 1
#    If "fs.protected_hardlinks" is not set to "1" or is missing, this is a finding.
#    Check that the configuration files are present to enable this kernel parameter.
#      $ sudo grep -r fs.protected_hardlinks /run/sysctl.d/*.conf /usr/local/lib/sysctl.d/*.conf /usr/lib/sysctl.d/*.conf /lib/sysctl.d/*.conf /etc/sysctl.conf /etc/sysctl.d/*.conf
#        /etc/sysctl.d/99-sysctl.conf:fs.protected_hardlinks = 1
#    If "fs.protected_hardlinks" is not set to "1", is missing or commented out, this is a finding.
#    If conflicting results are returned, this is a finding.
#  description: |-
#    Discretionary Access Control (DAC) is based on the notion that individual users are "owners" of objects and therefore have discretion over who should be authorized to access the object and in which mode (e.g., read or write). Ownership is usually acquired as a consequence of creating the object or via specified ownership assignment. DAC allows the owner to determine who will have access to objects they control. An example of DAC includes user-controlled file permissions.
#    When discretionary access control policies are implemented, subjects are not constrained with regard to what actions they can take with information for which they have already been granted access. Thus, subjects that have been granted access to information are not prevented from passing (i.e., the subjects have the discretion to pass) the information to other subjects or objects. A subject that is constrained in its operation by Mandatory Access Control policies is still able to operate under the less rigorous constraints of this requirement. Thus, while Mandatory Access Control imposes constraints preventing a subject from passing information to another subject operating at a different sensitivity level, this requirement permits the subject to pass the information to any subject at the same sensitivity level. The policy is bounded by the information system boundary. Once the information is passed outside the control of the information system, additional means may be required to ensure the constraints remain in effect. While the older, more traditional definitions of discretionary access control require identity-based access control, that limitation is not required for this use of discretionary access control.
#    By enabling the fs.protected_hardlinks kernel parameter, users can no longer create soft or hard links to files they do not own. Disallowing such hardlinks mitigate vulnerabilities based on insecure file system accessed by privileged programs, avoiding an exploitation vector exploiting unsafe use of open() or creat().
#  Satisfies: SRG-OS-000312-GPOS-00122, SRG-OS-000324-GPOS-00125
#  fixid: F-56540r825082_fix
#  fixtext: |-
#    Configure the operating system to enable DAC on hardlinks.
#    Add or edit the following line in a system configuration file, in the "/etc/sysctl.d/" directory:
#      fs.protected_hardlinks = 1
#    Load settings from all system configuration files with the following command:
#      $ sudo sysctl --system


- name: TOSS-04-040960 - TOSS must enable kernel parameters to enforce discretionary access control on hardlinks.
  ansible.posix.sysctl:
    name: fs.protected_hardlinks
    value: 1
    state: present
    reload: true
  when:
    - toss_04_040960 | bool
  tags:
    - V-253137
    - SRG-OS-000312-GPOS-00122
    - TOSS-04-040960
    - DISA-STIG-TOSS-04-040960
    - medium_severity
    - CCI-002165
    - CCI-002235
