# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253122

# To verify that null passwords cannot be used, run the following command:
#
#     $ sudo grep -i nullok /etc/pam.d/password-auth
#
# If output is produced, this is a finding.


- name: TOSS-04-040810 - TOSS must not allow blank or null passwords in the password-auth file.
  ansible.builtin.replace:
    path: '/etc/pam.d/{{ pam_auth_file }}'
    regexp: '(nullok_secure|nullok)'
    backup: true
  loop:
    - password-auth
  loop_control:
    loop_var: pam_auth_file
  when:
    - toss_04_040810 | bool
  tags:
    - V-253122
    - SRG-OS-000480-GPOS-00227
    - TOSS-04-040810
    - DISA-STIG-TOSS-04-040810
    - high_severity
    - CCI-000366
    - NASA-ASCS-20165
