# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253118

# Verify TOSS ignores IPv4 ICMP redirect messages. Note: If IPv4 is
# disabled on the system, this requirement is Not Applicable. Check the value of
# the "accept_redirects" variables with the following command: $ sudo sysctl
# net.ipv4.conf.all.accept_redirects net.ipv4.conf.all.accept_redirects = 0 If the
# returned line does not have a value of "0", a line is not returned, or the line
# is commented out, this is a finding.


- name: TOSS-04-040770 - TOSS must ignore IPv4 Internet Control Message Protocol (ICMP) redirect messages.
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^(?i)#?net.ipv4.conf.all.accept_redirects'
    line: 'net.ipv4.conf.all.accept_redirects = 0'
    state: present
    backup: true
  notify: Reload sysctl
  when:
    - toss_04_040770 | bool
  tags:
    - V-253118
    - SRG-OS-000480-GPOS-00227
    - SV-253118r825026_rule
    - TOSS-04-040770
    - DISA-STIG-TOSS-04-040770
    - medium_severity
    - CCI-000366
    - NASA-ASCS-20190
