# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253025

# Verify TOSS generates audit records for all account creations,
# modifications, disabling, and termination events that affect "/etc/gshadow".
# Check the auditing rules in "/etc/audit/audit.rules" with the following command:
# $ sudo grep /etc/gshadow /etc/audit/audit.rules -w /etc/gshadow -p wa -k
# identity If the command does not return a line, or the line is commented out,
# this is a finding.


- name: TOSS-04-030800 - TOSS must generate audit records for all account creations, modifications, disabling, and termination events that affect "/etc/gshadow".
  ansible.builtin.lineinfile:
    path: /etc/audit/audit.rules
    line: -w /etc/gshadow -p wa -k identity
  notify: Build auditd rules
  when:
    - toss_04_030800 | bool
  tags:
    - V-253025
    - SRG-OS-000303-GPOS-00120
    - SV-253025r824747_rule
    - TOSS-04-030800
    - DISA-STIG-TOSS-04-030800
    - medium_severity
    - CCI-002130
