# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253069

# Verify TOSS enforces a minimum 15-character password length. The "minlen"
# option sets the minimum number of characters in a new password.
#
# Check for the value of the "minlen" option in "/etc/security/pwquality.conf"
# with the following command:
#
#     $ sudo grep minlen /etc/security/pwquality.conf
#     minlen = 15
#
# If the command does not return a "minlen" value of 15 or greater,
# this is a finding.


- name: TOSS-04-040140 - TOSS must enforce a minimum 15-character password length.
  ansible.builtin.lineinfile:
    path: /etc/security/pwquality.conf
    regexp: '^#?\s*minlen'
    line: 'minlen = {{ pwquality_minlen }}'
    backup: true
  when:
    - toss_04_040140 | bool
  tags:
    - V-253069
    - SRG-OS-000078-GPOS-00046
    - TOSS-04-040140
    - DISA-STIG-TOSS-04-040140
    - medium_severity
    - CCI-000205
