# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253090

# Verify TOSS accepts PIV credentials.
#
# Check that the "opensc" package is installed on the system with the
# following command:
#
#     $ sudo yum list installed opensc
#     opensc.x86_64 0.20.0-4.el8 @anaconda
#
# Check that "opensc" accepts PIV cards with the following command:
#
#     $ sudo opensc-tool --list-drivers | grep -i piv
#     PIV-II Personal Identity Verification Card
#
# If the "opensc" package is not installed and the "opensc-tool" driver
# list does not include "PIV-II", this is a finding.


- name: TOSS-04-040420 - TOSS must accept Personal Identity Verification (PIV) credentials.
  block:
    - name: TOSS-04-040420 - Ensure opensc is installed
      ansible.builtin.package:
        name: opensc
        state: present
    - name: TOSS-04-040420 - Ensure opensc accepts PIV cards
      ansible.builtin.shell: "set -o pipefail && opensc-tool --list-drivers | grep -i piv"
      changed_when: false
      check_mode: false
      # failed_when: "PIV-II" not in piv_drivers.stdout # TODO -- This doesn't work this way, need to re-implement
  when:
    - toss_04_040420 | bool
  tags:
    - V-253090
    - SRG-OS-000376-GPOS-00161
    - TOSS-04-040420
    - DISA-STIG-TOSS-04-040420
    - medium_severity
    - CCI-001953
