# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253095

# Ensure TOSS verifies correct operation of all security functions.
#
# Check if "SELinux" is active and is enforcing the targeted policy with
# the following command:
#
#     $ sudo sestatus
#     SELinux status: enabled
#     SELinuxfs mount: /sys/fs/selinux
#     SELinux root directory: /etc/selinux
#     Loaded policy name: targeted
#     Current mode: enforcing
#     Mode from config file: enforcing
#     Policy MLS status: enabled
#     Policy deny_unknown status: allowed
#     Memory protection checking: actual (secure)
#     Max kernel policy version: 33
#
# If the "Loaded policy name" is not set to "targeted", this is a finding.
#
# Verify that the /etc/selinux/config file is configured to the "SELINUXTYPE"
# to "targeted":
#
#     $ sudo grep -i "selinuxtype" /etc/selinux/config | grep -v '^#'
#     SELINUXTYPE = targeted
#
# If no results are returned or "SELINUXTYPE" is not set to "targeted",
# this is a finding.


- name: TOSS-04-040510 - TOSS must enable the "SELinux" targeted policy.
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUXTYPE=targeted'
    line: 'SELINUXTYPE=targeted'
    state: present
  when:
    - toss_04_040510 | bool
  tags:
    - CCI-002696
    - DISA-STIG-RHEL-08-010450
    - DISA-STIG-TOSS-04-040510
    - hpc_issue
    - medium_severity
    - SRG-OS-000445-GPOS-00199
    - TOSS-04-040510
    - V-253095
