# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253041

# Verify that an audit event is generated for any
# successful/unsuccessful use of the "gpasswd" command by performing the following
# command to check the file system rules in "/etc/audit/audit.rules": $ sudo grep
# -w gpasswd /etc/audit/audit.rules -a always,exit -F path=/usr/bin/gpasswd -F
# perm=x -F auid>=1000 -F auid!=unset -k privileged If the command does not
# return a line, or the line is commented out, this is a finding.


- name: TOSS-04-031150 - Successful/unsuccessful uses of the "gpasswd" command in TOSS must generate an audit record.
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/audit.rules
    line: -a always,exit -F path=/usr/bin/gpasswd -F perm=x -F auid>=1000 -F auid!=unset -k privileged
  notify: Build auditd rules
  when:
    - toss_04_031150 | bool
  tags:
    - V-253041
    - SRG-OS-000471-GPOS-00215
    - SV-253041r824795_rule
    - TOSS-04-031150
    - DISA-STIG-TOSS-04-031150
    - medium_severity
    - CCI-000172
