# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-252923

# Verify that TOSS displays the Standard Mandatory DoD Notice and Consent Banner
# or equivalent US Government Agency Notice and Consent Banner before granting
# access to the system when connecting from outside of the cluster.
#
# Check for the location of the banner file being used with the following command:
#
#     $ sudo grep -i banner /etc/ssh/sshd_config
#     banner /etc/issue
#
# This command will return the banner keyword and the name of the file that
# contains the ssh banner (in this case "/etc/issue").
#
# If the line is commented out, this is a finding.
#
# For nodes of the cluster that are only privately (within the cluster) accessible,
# this requirement is Not Applicable.
#
# View the file specified by the banner keyword to check that it matches the text
# of the Standard Mandatory DoD Notice and Consent Banner:
#
#     "You are accessing a U.S. Government (USG) Information System (IS) that is
#     provided for USG-authorized use only.
#
#     By using this IS (which includes any device attached to this IS), you consent
#     to the following conditions:
#
#     -The USG routinely intercepts and monitors communications on this IS for
#     purposes including, but not limited to, penetration testing, COMSEC monitoring,
#     network operations and defense, personnel misconduct (PM), law enforcement
#     (LE), and counterintelligence (CI) investigations.
#
#     -At any time, the USG may inspect and seize data stored on this IS.
#
#     -Communications using, or data stored on, this IS are not private, are
#     subject to routine monitoring, interception, and search, and may be disclosed
#     or used for any USG-authorized purpose.
#
#     -This IS includes security measures (e.g., authentication and access controls)
#     to protect USG interests--not for your personal benefit or privacy.
#
#     -Notwithstanding the above, using this IS does not constitute consent to PM,
#     LE or CI investigative searching or monitoring of the content of privileged
#     communications, or work product, related to personal representation or
#     services by attorneys, psychotherapists, or clergy, and their assistants. Such
#     communications and work product are private and confidential. See User
#     Agreement for details."
#
#     If the system has a graphical logon capability and does not display a
#     graphical logon banner, this is a finding.
#
#     If the text in the file does not match the Standard Mandatory DoD Notice
#     and Consent Banner or equivalent US Government Agency Notice and Consent
#     Banner, this is a finding.


- name: TOSS-04-010120 - TOSS must display the Standard Mandatory DoD Notice and Consent Banner or equivalent US Government Agency Notice and Consent Banner before granting local or remote access to the system via a ssh logon.
  block:
    - name: TOSS-04-010120 - Check `Banner` in sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^(?i)#?Banner'
        line: 'Banner /etc/issue'
        state: present
        backup: true
        validate: /usr/sbin/sshd -t -f %s
      notify: Restart sshd
  when:
    - toss_04_010120 | bool
    # - not (compute_node | bool)  # Not applicable on compute nodes - # TODO need a universal way to check this.
  tags:
    - V-252923
    - SRG-OS-000228-GPOS-00088
    - TOSS-04-010120
    - DISA-STIG-TOSS-04-010120
    - low_severity
    - CCI-001384
    - CCI-001385
    - CCI-001386
    - CCI-001387
    - CCI-001388
