# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253014

# Verify TOSS generates an audit record when successful/unsuccessful attempts
# to use the "fchown" system call by performing the following command to check
# the file system rules in "/etc/audit/audit.rules":
#
#     $ sudo grep -w fchown /etc/audit/audit.rules
#     -a always,exit -F arch=b32 -S fchown -F auid>=1000 -F auid!=unset -k perm_mod
#     -a always,exit -F arch=b64 -S fchown -F auid>=1000 -F auid!=unset -k perm_mod
#
# If the command does not return a line, or the line is commented out,
# this is a finding.

# Verify TOSS generates an audit record when successful/unsuccessful attempts to use the "fchownat" system call by performing the following command to check the file system rules in "/etc/audit/audit.rules":
#
#     $ sudo grep -w fchownat /etc/audit/audit.rules
#     -a always,exit -F arch=b32 -S fchownat -F auid>=1000 -F auid!=unset -k perm_mod
#     -a always,exit -F arch=b64 -S fchownat -F auid>=1000 -F auid!=unset -k perm_mod
#
# If the command does not return a line, or the line is commented out,
# this is a finding.


- name: TOSS-04-030610 - Successful/unsuccessful uses of the fchown system call in TOSS must generate an audit record.
  block:
    - name: TOSS-04-030610 - Successful/unsuccessful uses of the fchown system call, esp. arch=b32
      ansible.builtin.lineinfile:
        path: /etc/audit/rules.d/audit.rules
        line: -a always,exit -F arch=b32 -S fchown -F auid>=1000 -F auid!=unset -k perm_mod
      notify: Build auditd rules
    - name: TOSS-04-030610 - Successful/unsuccessful uses of the fchown system call, esp. arch=b64
      ansible.builtin.lineinfile:
        path: /etc/audit/rules.d/audit.rules
        line: -a always,exit -F arch=b64 -S fchown -F auid>=1000 -F auid!=unset -k perm_mod
      notify: Build auditd rules
  when:
    - toss_04_030610 | bool
  tags:
    - V-253014
    - SRG-OS-000064-GPOS-00033
    - TOSS-04-030610
    - DISA-STIG-TOSS-04-030610
    - medium_severity
    - CCI-000172
