# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-252998

# Verify that an audit event is generated for any
# successful/unsuccessful use of the "renameat" command by performing the
# following command to check the file system rules in "/etc/audit/audit.rules": $
# sudo grep -w "renameat" /etc/audit/audit.rules -a always,exit -F arch=b32 -S
# renameat -F auid>=1000 -F auid!=unset -k delete -a always,exit -F arch=b64 -S
# renameat -F auid>=1000 -F auid!=unset -k delete If the command does not
# return a line, or the line is commented out, this is a finding.


- name: TOSS-04-030440 - Successful/unsuccessful uses of the "renameat" command in TOSS must generate an audit record.
  block:
    - ansible.builtin.lineinfile:
        path: /etc/audit/audit.rules
        line: -a always,exit -F arch=b32 -S renameat -F auid>=1000 -F auid!=unset -k delete
      notify: Build auditd rules
    - ansible.builtin.lineinfile:
        path: /etc/audit/audit.rules
        line: -a always,exit -F arch=b64 -S renameat -F auid>=1000 -F auid!=unset -k delete
      notify: Build auditd rules
  when:
    - toss_04_030440 | bool
  tags:
    - V-252998
    - SRG-OS-000037-GPOS-00015
    - SV-252998r824318_rule
    - TOSS-04-030440
    - DISA-STIG-TOSS-04-030440
    - medium_severity
    - CCI-000130
    - CCI-000135
    - CCI-000169
    - CCI-000172
    - CCI-002884
