# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-252994

# Verify that an audit event is generated for any successful/unsuccessful
# use of the "pam_timestamp_check" command by performing the following command
# to check the file system rules in "/etc/audit/audit.rules":
#
#     $ sudo grep -w pam_timestamp_check /etc/audit/audit.rules
#     -a always,exit -F path=/usr/sbin/pam_timestamp_check -F perm=x -F auid>=1000 -F auid!=unset -k privileged-pam_timestamp_check
#
# If the command does not return a line, or the line is commented out,
# this is a finding.


- name: TOSS-04-030400 - Successful/unsuccessful uses of the "pam_timestamp_check" command in TOSS must generate an audit record.
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/audit.rules
    line: -a always,exit -F path=/usr/sbin/pam_timestamp_check -F perm=x -F auid>=1000 -F auid!=unset -k privileged-pam_timestamp_check
  notify: Build auditd rules
  when:
    - toss_04_030400 | bool
  tags:
    - V-252994
    - SRG-OS-000037-GPOS-00015
    - TOSS-04-030400
    - DISA-STIG-TOSS-04-030400
    - medium_severity
    - CCI-000130
    - CCI-000135
    - CCI-000169
    - CCI-000172
    - CCI-002884
