# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-252966

# To verify that null passwords cannot be used, run the following command:
#
#     $ sudo grep -i permitemptypasswords /etc/ssh/sshd_config
#     PermitEmptyPasswords no
#
# If "PermitEmptyPasswords" is set to "yes", this is a finding.


- name: TOSS-04-020270 - TOSS must not allow accounts configured with blank or null passwords.
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(?i)#?PermitEmptyPasswords'
    line: 'PermitEmptyPasswords no'
    state: present
    backup: true
    validate: /usr/sbin/sshd -t -f %s
  notify: Restart sshd
  when:
    - toss_04_020270 | bool
  tags:
    - V-252966
    - SRG-OS-000480-GPOS-00227
    - TOSS-04-020270
    - DISA-STIG-TOSS-04-020270
    - high_severity
    - CCI-000366
    - NASA-ASCS-40061
