# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253104

# Verify the file integrity tool is configured to verify ACLs.
#
# Note: AIDE is highly configurable at install time. This requirement assumes
# the "aide.conf" file is under the "/etc" directory.
#
# If AIDE is not installed, ask the System Administrator how file integrity
# checks are performed on the system.
#
# Use the following command to determine if the file is in a location other
# than "/etc/aide/aide.conf":
#
#     $ sudo find / -name aide.conf
#
# Check the "aide.conf" file to determine if the "acl" rule has been added
# to the rule list being applied to the files and directories selection lists
# with the following command:
#
#     $ sudo egrep "[+]?acl" /etc/aide.conf
#     VarFile = OwnerMode+n+l+X+acl
#
# If the "acl" rule is not being used on all selection lines in the
# "/etc/aide.conf" file, is commented out, or ACLs are not being checked by
# another file integrity tool, this is a finding.


- name: TOSS-04-040630 - The TOSS file integrity tool must be configured to verify Access Control Lists (ACLs).
  block:
    - name: TOSS-04-040630 - The TOSS file integrity tool must be configured to verify Access Control Lists (ACLs). Check DIR.
      ansible.builtin.lineinfile:
        path: /etc/aide/aide.conf
        regexp: DIR = p+i+n+u+g+acl+selinux+xattrs
        line: DIR = p+i+n+u+g+acl+selinux+xattrs
        state: present
        mode: '600'
        create: true
    - name: TOSS-04-040630 - The TOSS file integrity tool must be configured to verify Access Control Lists (ACLs). Check NORMAL.
      ansible.builtin.lineinfile:
        path: /etc/aide/aide.conf
        regexp: NORMAL = p+i+n+u+g+s+m+c+acl+selinux+xattrs+sha512
        line: NORMAL = p+i+n+u+g+s+m+c+acl+selinux+xattrs+sha512
        state: present
        mode: '600'
        create: true
  when:
    - toss_04_040630 | bool
  tags:
    - CCI-000366
    - DISA-STIG-TOSS-04-040630
    - low_severity
    - SRG-OS-000480-GPOS-00227
    - TOSS-04-040630
    - V-253104
