# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-252919

# Verify the OpenSSL library is configured to use only DoD-approved TLS encryption:
#
#     $ sudo grep -i MinProtocol /etc/crypto-policies/back-ends/opensslcnf.config
#     TLS.MinProtocol = TLSv1.2
#     DTLS.MinProtocol = DTLSv1.2
#
# If the "TLS.MinProtocol" is set to anything older than "TLSv1.2" or the
# "DTLS.MinProtocol" is set to anything older than DTLSv1.2, this is a finding.


- name: TOSS-04-010080 - The TOSS operating system must implement DoD-approved encryption in the OpenSSL package.
  block:
    - name: TOSS-04-010080 - Check for duplicate values of TLS.MinProtocol in /etc/crypto-policies/back-ends/opensslcnf.config
      ansible.builtin.lineinfile:
        path: /etc/crypto-policies/back-ends/opensslcnf.config
        create: false
        regexp: (?i)^\s*TLS.MinProtocol\s+
        state: absent
      check_mode: true
      changed_when: false
      register: dupes
    - name: TOSS-04-010080 - Deduplicate values of TLS.MinProtocol from /etc/crypto-policies/back-ends/opensslcnf.config
      ansible.builtin.lineinfile:
        path: /etc/crypto-policies/back-ends/opensslcnf.config
        create: false
        regexp: (?i)^\s*TLS.MinProtocol\s+
        state: absent
      when: dupes.found is defined and dupes.found > 1
    - name: TOSS-04-010080 - Insert correct line of TLS.MinProtocol to /etc/crypto-policies/back-ends/opensslcnf.config
      ansible.builtin.lineinfile:
        path: /etc/crypto-policies/back-ends/opensslcnf.config
        create: true
        regexp: (?i)^\s*TLS.MinProtocol\s+
        line: TLS.MinProtocol = TLSv1.2
        state: present
        mode: '0644'
    - name: TOSS-04-010080 - Check for duplicate values of DTLS.MinProtocol in /etc/crypto-policies/back-ends/opensslcnf.config
      ansible.builtin.lineinfile:
        path: /etc/crypto-policies/back-ends/opensslcnf.config
        create: false
        regexp: (?i)^\s*DTLS.MinProtocol\s+
        state: absent
      check_mode: true
      changed_when: false
      register: dupes
    - name: TOSS-04-010080 - Deduplicate values of DTLS.MinProtocol from /etc/crypto-policies/back-ends/opensslcnf.config
      ansible.builtin.lineinfile:
        path: /etc/crypto-policies/back-ends/opensslcnf.config
        create: false
        regexp: (?i)^\s*DTLS.MinProtocol\s+
        state: absent
      when: dupes.found is defined and dupes.found > 1
    - name: TOSS-04-010080 - Insert correct line of DTLS.MinProtocol to /etc/crypto-policies/back-ends/opensslcnf.config
      ansible.builtin.lineinfile:
        path: /etc/crypto-policies/back-ends/opensslcnf.config
        create: true
        regexp: (?i)^\s*DTLS.MinProtocol\s+
        line: DTLS.MinProtocol = DTLSv1.2
        state: present
        mode: '0644'
  when:
    - toss_04_010080 | bool
  tags:
    - V-252919
    - SRG-OS-000125-GPOS-00065
    - TOSS-04-010080
    - DISA-STIG-TOSS-04-010080
    - medium_severity
    - CCI-000877
    - CCI-001453
