# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-252996

# Verify that an audit event is generated for any
# successful/unsuccessful use of the "init_module" command by performing the
# following command to check the file system rules in "/etc/audit/audit.rules": $
# sudo grep -w "init_module" /etc/audit/audit.rules -a always,exit -F arch=b32 -S
# init_module -F auid>=1000 -F auid!=unset -k module_chng -a always,exit -F
# arch=b64 -S init_module -F auid>=1000 -F auid!=unset -k module_chng If the
# command does not return a line, or the line is commented out, this is a finding.


- name: TOSS-04-030420 - Successful/unsuccessful uses of the "init_module" command in TOSS must generate an audit record.
  block:
    - ansible.builtin.lineinfile:
        path: /etc/audit/audit.rules
        line: -a always,exit -F arch=b32 -S init_module -F auid>=1000 -F auid!=unset -k module_chng
      notify: Build auditd rules
    - ansible.builtin.lineinfile:
        path: /etc/audit/audit.rules
        line: -a always,exit -F arch=b64 -S init_module -F auid>=1000 -F auid!=unset -k module_chng
      notify: Build auditd rules
  when:
    - toss_04_030420 | bool
  tags:
    - V-252996
    - SRG-OS-000037-GPOS-00015
    - SV-252996r824312_rule
    - TOSS-04-030420
    - DISA-STIG-TOSS-04-030420
    - medium_severity
    - CCI-000130
    - CCI-000135
    - CCI-000169
    - CCI-000172
    - CCI-002884
