# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253109

# Verify TOSS is not configured to reboot the system when
# Ctrl-Alt-Delete is pressed with the following command:
#
#     $ sudo systemctl status ctrl-alt-del.target
#     ctrl-alt-del.target
#     Loaded: masked (Reason: Unit ctrl-alt-del.target is masked.)
#     Active: inactive (dead)
#
# If the "ctrl-alt-del.target" is loaded and not masked, this is a finding.


- name: TOSS-04-040680 - The x86 Ctrl-Alt-Delete key sequence must be disabled on TOSS.
  ansible.builtin.systemd:
    name: ctrl-alt-del.target
    state: stopped
    enabled: false
    masked: true
  when:
    - toss_04_040680 | bool
  tags:
    - V-253109
    - SRG-OS-000480-GPOS-00227
    - TOSS-04-040680
    - DISA-STIG-TOSS-04-040680
    - high_severity
    - CCI-000366
