# https://www.stigviewer.com/stig/toss_4/2023-xx-xx/finding/V-253029

# Verify TOSS generates audit records for all account creations,
# modifications, disabling, and termination events that affect "/etc/sudoers.d/".
# Check the auditing rules in "/etc/audit/audit.rules" with the following command:
# $ sudo grep /etc/sudoers.d/ /etc/audit/audit.rules -w /etc/sudoers.d/ -p wa -k
# identity If the command does not return a line, or the line is commented out,
# this is a finding.


- name: TOSS-04-030850 - TOSS must generate audit records for all account creations, modifications, disabling, and termination events that affect "/etc/sudoers.d/".
  ansible.builtin.lineinfile:
    path: /etc/audit/audit.rules
    line: -w /etc/sudoers.d/ -p wa -k identity
  notify: Build auditd rules
  when:
    - toss_04_030850 | bool
  tags:
    - V-253029
    - SRG-OS-000303-GPOS-00120
    - SV-253029r824759_rule
    - TOSS-04-030850
    - DISA-STIG-TOSS-04-030850
    - medium_severity
    - CCI-002130
