# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-252960

# Verify all local interactive users on TOSS are assigned a home
# directory upon creation with the following command: $ sudo grep -i create_home
# /etc/login.defs CREATE_HOME yes If the value for "CREATE_HOME" parameter is not
# set to "yes", the line is missing, or the line is commented out, this is a
# finding.

# Verify all local interactive users on TOSS are assigned a home directory
# upon creation with the following command:
#
#     $ sudo grep -i create_home /etc/login.defs
#     CREATE_HOME yes
#
# If the value for "CREATE_HOME" parameter is not set to "yes", the line is
# missing, or the line is commented out, this is a finding.


- name: TOSS-04-020200 - All TOSS local interactive user accounts must be assigned a home directory upon creation.
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    line: CREATE_HOME yes
  when:
    - toss_04_020200 | bool
  tags:
    - V-252960
    - SRG-OS-000480-GPOS-00227
    - TOSS-04-020200
    - DISA-STIG-TOSS-04-020200
    - medium_severity
    - CCI-000366
