# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253031

# Verify TOSS allocates audit record storage capacity to store at least one
# week of audit records when audit records are not immediately sent to a
# central audit record storage facility.
#
# If logs are immediately sent to a central audit record storage facility,
# this requirement is Not Applicable.
#
# Determine to which partition the audit records are being written with
# the following command:
#
#     $ sudo grep log_file /etc/audit/auditd.conf
#     log_file = /var/log/audit/audit.log
#
# Check the size of the partition to which audit records are written
# (with the example being /var/log/audit/) with the following command:
#
#     $ sudo df -h /var/log/audit/audit.log
#     /dev/sda2 24G 10.4G 13.6G 43% /var/log/audit
#
# If the audit records are not written to a partition made specifically
# for audit records (/var/log/audit is a separate partition), determine
# the amount of space being used by other files in the partition with
# the following command:
#
#     $ sudo du -sh [audit_partition]
#     1.8G /var/log/audit
#
# If the audit record partition is not allocated for sufficient storage
# capacity, this is a finding.
#
# Note: The partition size needed to capture a week of audit records is
# based on the activity level of the system and the total storage
# capacity available. Typically, 10.0 GB of storage space for audit
# records should be sufficient.


- name: TOSS-04-030890 - TOSS must allocate audit record storage capacity to store at least one week's worth of audit records, when audit records are not immediately sent to a central audit record storage facility.
  block:
    - name: TOSS-04-030890 - Determine to which partition the audit records are being written
      ansible.builtin.command: "grep log_file /etc/audit/auditd.conf"
      changed_when: false
      check_mode: false
      failed_when: log_file.rc not in [0,1]
      register: log_file
    - name: TOSS-04-030890 - Get the size of the partition to which audit records are written
      ansible.builtin.command: "df -h {{ log_file.stdout.split().2 }}"
      changed_when: false
      check_mode: false
      register: disk_space
    - name: TOSS-04-030890 - Get the basename of the partition path
      ansible.builtin.set_fact:
        audit_partition: '{{ log_file.stdout.split().2 | ansible.builtin.dirname }}'
    - name: TOSS-04-030890 - Determine the amount of space being used by other files in the partition
      ansible.builtin.command: "du -sh {{ audit_partition }}"
      changed_when: false
      check_mode: false
      register: disk_space_partition
    - name: TOSS-04-030890 - Display size of the partition audit records are written to
      ansible.builtin.debug:
        var: disk_space.stdout
        verbosity: 1
    - name: TOSS-04-030890 - Display the amount of space being used by the other files in the partition
      ansible.builtin.debug:
        var: disk_space_partition.stdout
        verbosity: 1
  when:
    - toss_04_030890 | bool
  tags:
    - V-253031
    - SRG-OS-000341-GPOS-00132
    - TOSS-04-030890
    - DISA-STIG-TOSS-04-030890
    - medium_severity
    - CCI-001849
    - DISA-STIG-RHEL-08-030660
    - manual
