# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-252953

# Verify the account identifiers (individuals, groups, roles, and devices)
# are disabled after 35 days of inactivity with the following command:
#
# Check the account inactivity value by performing the following command:
#
#     $ sudo grep -i inactive /etc/default/useradd
#     INACTIVE=35
#
# If "INACTIVE" is set to "-1", a value greater than "35", or is commented
# out, this is a finding.


- name: TOSS-04-020120 - TOSS must disable account identifiers (individuals, groups, roles, and devices) after 35 days of inactivity.
  ansible.builtin.lineinfile:
    path: /etc/default/useradd
    regexp: '^#?INACTIVE'
    line: 'INACTIVE=35'
  when:
    - toss_04_020120 | bool
  tags:
    - V-252953
    - SRG-OS-000118-GPOS-00060
    - TOSS-04-020120
    - DISA-STIG-TOSS-04-020120
    - medium_severity
    - CCI-000795
    - NASA-ASCS-20001
