# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253056

# Verify that TOSS monitors all remote access methods.
#
# Check that remote access methods are being logged by running the following
# command:
#
#     $ sudo grep -E '(auth.*|authpriv.*|daemon.*)' /etc/rsyslog.conf
#     auth.*;authpriv.*;daemon.* /var/log/secure
#
# If any of "auth.*", "authpriv.*" or "daemon.*" are not configured to be
# logged, this is a finding.


- name: TOSS-04-040010 - TOSS must monitor remote access methods.
  block:
    - name: 'TOSS-04-040010 - Set facts'
      ansible.builtin.set_fact:
        conf_files:
          - /etc/rsyslog.conf
        remote_methods:
          - selector: auth.*
            regexp: ^.*auth\.\*.*$
          - selector: authpriv.*
            regexp: ^.*authpriv\.\*.*$
          - selector: daemon.*
            regexp: ^.*daemon\.\*.*$
    - name: 'TOSS-04-040010 - Ensure rsyslog.conf exists'
      ansible.builtin.file:
        path: '{{ conf_files.0 }}'
        state: touch
        mode: '0644'
    - name: 'TOSS-04-040010 - Gather conf.d files'
      ansible.builtin.find:
        patterns:
          - '*.conf'
        paths:
          - /etc/rsyslog.d
      register: rsyslogd
    - name: 'TOSS-04-040010 - Set conf file(s)'
      ansible.builtin.set_fact:
        conf_files: '{{ conf_files + [item.path] }}'
      loop: '{{ rsyslogd.files }}'
    - name: 'TOSS-04-040010 - Check for existing values'
      ansible.builtin.lineinfile:
        path: '{{ item.1 }}'
        regexp: '{{ item.0.regexp }}'
        state: absent
      check_mode: true
      changed_when: false
      register: remote_method_values
      loop: '{{ remote_methods | product(conf_files) | list }}'
    - name: 'TOSS-04-040010 - Configure'
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.conf
        regexp: '{{ item.item.0.regexp }} .*\/var\/log\/secure.*$'
        line: '{{ item.item.0.selector }} /var/log/secure'
        insertafter: ^.*\/var\/log\/secure.*$
        create: true
        mode: '0644'
      loop: '{{ remote_method_values.results }}'
      notify: Restart rsyslog
  when:
    - toss_04_040010 | bool
  tags:
    - V-253056
    - SRG-OS-000032-GPOS-00013
    - TOSS-04-040010
    - DISA-STIG-TOSS-04-040010
    - medium_severity
    - CCI-000067
    - DISA-STIG-RHEL-08-010070
