---

  - name: restart rsyslog
    ansible.builtin.systemd:
      name: rsyslog
      state: restarted

  - name: restart sshd
    ansible.builtin.systemd:
      name: sshd
      state: restarted

  - name: reload firewall
    ansible.builtin.systemd:
      name: firewalld
      state: restarted

  - name: reload sysctl
    ansible.builtin.command: sysctl --system
